package PeerToPeer.FilePackage;


/**
* PeerToPeer/FilePackage/dataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adapter/PeerToPeerIDL.idl
* Quinta-feira, 10 de Outubro de 2019 14h19min09s BRT
*/

public final class dataHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public dataHolder ()
  {
  }

  public dataHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PeerToPeer.FilePackage.dataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PeerToPeer.FilePackage.dataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PeerToPeer.FilePackage.dataHelper.type ();
  }

}
