module ListManager{
	interface Manager{
		void addClient (in string client);
		void removeClient (in string client);
		void addFileToClient (in string client, in string fileName);
		void removeFileFromClient (in string client, in string fileName);
		string clientWhoHasTheFile(in string fileName);
		string generateNewClientName ();
		string printList ();
	};
};
