package ListManager.ManagerPackage;


/**
* ListManager/ManagerPackage/stringListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adapter/ListManagerIDL.idl
* Segunda-feira, 14 de Outubro de 2019 23h08min44s BRT
*/

public final class stringListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public stringListHolder ()
  {
  }

  public stringListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ListManager.ManagerPackage.stringListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ListManager.ManagerPackage.stringListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ListManager.ManagerPackage.stringListHelper.type ();
  }

}
