package ListManager;


/**
* ListManager/ManagerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ListManagerIDL.idl
* Domingo, 6 de Outubro de 2019 12h44min12s BRT
*/

abstract public class ManagerHelper
{
  private static String  _id = "IDL:ListManager/Manager:1.0";

  public static void insert (org.omg.CORBA.Any a, ListManager.Manager that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ListManager.Manager extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ListManager.ManagerHelper.id (), "Manager");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ListManager.Manager read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ManagerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ListManager.Manager value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ListManager.Manager narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ListManager.Manager)
      return (ListManager.Manager)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ListManager._ManagerStub stub = new ListManager._ManagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ListManager.Manager unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ListManager.Manager)
      return (ListManager.Manager)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ListManager._ManagerStub stub = new ListManager._ManagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
