package ListManager;


/**
* ListManager/ManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adapter/ListManagerIDL.idl
* Segunda-feira, 14 de Outubro de 2019 23h08min44s BRT
*/

public interface ManagerOperations 
{
  void addClient (String client);
  void removeClient (String client);
  void addFileToClient (String client, String fileName);
  void removeFileFromClient (String client, String fileName);
  String clientWhoHasTheFile (String fileName);
  String[] clientsWhoHasTheFile (String fileName);
  String generateNewClientName ();
  String printList ();
} // interface ManagerOperations
