package ListManager;


/**
* ListManager/Manager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ListManagerIDL.idl
* Domingo, 6 de Outubro de 2019 12h44min12s BRT
*/

public interface Manager extends ManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Manager
