package ListManager;


/**
* ListManager/Manager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adapter/ListManagerIDL.idl
* Terça-feira, 15 de Outubro de 2019 00h33min52s BRT
*/

public interface Manager extends ManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Manager
