package ListManager;

/**
* ListManager/ManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adapter/ListManagerIDL.idl
* Domingo, 6 de Outubro de 2019 23h55min02s BRT
*/

public final class ManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public ListManager.Manager value = null;

  public ManagerHolder ()
  {
  }

  public ManagerHolder (ListManager.Manager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ListManager.ManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ListManager.ManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ListManager.ManagerHelper.type ();
  }

}
