package ListManager;


/**
* ListManager/ManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adapter/ListManagerIDL.idl
* Domingo, 6 de Outubro de 2019 22h21min36s BRT
*/

public interface ManagerOperations 
{
  void addClient (String client);
  void removeClient (String client);
  void addFileToClient (String client, String fileName);
  void removeFileFromClient (String client, String fileName);
  void printList ();
} // interface ManagerOperations
