package ListManager;


/**
* ListManager/ManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adapter/ListManagerIDL.idl
* Domingo, 13 de Outubro de 2019 19h10min13s BRT
*/

public interface ManagerOperations 
{
  void addClient (String client);
  void removeClient (String client);
  void addFileToClient (String client, String fileName);
  void removeFileFromClient (String client, String fileName);
  String clientWhoHasTheFile (String fileName);
  String generateNewClientName ();
  String printList ();
} // interface ManagerOperations
