package PeerToPeer;


/**
* PeerToPeer/FileOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adapter/PeerToPeerIDL.idl
* Quarta-feira, 9 de Outubro de 2019 22h57min49s BRT
*/

public interface FileOperations 
{
  String download (String fileName);
} // interface FileOperations
