package PeerToPeer;


/**
* PeerToPeer/File.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adapter/PeerToPeerIDL.idl
* Quinta-feira, 10 de Outubro de 2019 14h19min09s BRT
*/

public interface File extends FileOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface File
