package PeerToPeer;


/**
* PeerToPeer/File.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adapter/PeerToPeerIDL.idl
* Domingo, 13 de Outubro de 2019 22h11min44s BRT
*/

public interface File extends FileOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface File
