package PeerToPeer;

/**
* PeerToPeer/FileHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adapter/PeerToPeerIDL.idl
* Domingo, 13 de Outubro de 2019 22h11min44s BRT
*/

public final class FileHolder implements org.omg.CORBA.portable.Streamable
{
  public PeerToPeer.File value = null;

  public FileHolder ()
  {
  }

  public FileHolder (PeerToPeer.File initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PeerToPeer.FileHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PeerToPeer.FileHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PeerToPeer.FileHelper.type ();
  }

}
