package PeerToPeer;


/**
* PeerToPeer/FilePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adapter/PeerToPeerIDL.idl
* Domingo, 13 de Outubro de 2019 22h11min44s BRT
*/

public abstract class FilePOA extends org.omg.PortableServer.Servant
 implements PeerToPeer.FileOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("download", new java.lang.Integer (0));
    _methods.put ("changePublicPath", new java.lang.Integer (1));
    _methods.put ("getPublicPath", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PeerToPeer/File/download
       {
         String fileName = in.read_string ();
         byte $result[] = null;
         $result = this.download (fileName);
         out = $rh.createReply();
         PeerToPeer.FilePackage.dataHelper.write (out, $result);
         break;
       }

       case 1:  // PeerToPeer/File/changePublicPath
       {
         String newPathName = in.read_string ();
         this.changePublicPath (newPathName);
         out = $rh.createReply();
         break;
       }

       case 2:  // PeerToPeer/File/getPublicPath
       {
         String $result = null;
         $result = this.getPublicPath ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PeerToPeer/File:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public File _this() 
  {
    return FileHelper.narrow(
    super._this_object());
  }

  public File _this(org.omg.CORBA.ORB orb) 
  {
    return FileHelper.narrow(
    super._this_object(orb));
  }


} // class FilePOA
