package PeerToPeer;


/**
* PeerToPeer/FileOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adapter/PeerToPeerIDL.idl
* Domingo, 13 de Outubro de 2019 22h11min44s BRT
*/

public interface FileOperations 
{
  byte[] download (String fileName);
  void changePublicPath (String newPathName);
  String getPublicPath ();
} // interface FileOperations
